# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2021 The Elixir Team

name: "Run OSS Review Toolkit"
description: "Runs OSS Review Toolkit & generates SBoMs"
inputs:
  report-formats:
    description: "ORT Report Formats"
    required: true
  fail-on-violation:
    description: "Whether to fail on violation."
    required: false
    default: false
  upload-reports:
    description: "Whether to upload all reports"
    required: false
    default: false
  version:
    desctiption: "Elixir Version (Tag / SHA)"
    required: true

outputs:
  results-path:
    description: "See oss-review-toolkit/ort-ci-github-action action"
    value: "${{ steps.ort.outputs.results-path }}"
  results-sbom-cyclonedx-xml-path:
    description: "See oss-review-toolkit/ort-ci-github-action action"
    value: "${{ steps.ort.outputs.results-sbom-cyclonedx-xml-path }}"
  results-sbom-cyclonedx-json-path:
    description: "See oss-review-toolkit/ort-ci-github-action action"
    value: "${{ steps.ort.outputs.results-sbom-cyclonedx-json-path }}"
  results-sbom-spdx-yml-path:
    description: "See oss-review-toolkit/ort-ci-github-action action"
    value: "${{ steps.ort.outputs.results-sbom-spdx-yml-path }}"
  results-sbom-spdx-json-path:
    description: "See oss-review-toolkit/ort-ci-github-action action"
    value: "${{ steps.ort.outputs.results-sbom-spdx-json-path }}"

runs:
  using: "composite"
  steps:
    - name: Fetch Default ORT Config
      id: fetch-default-ort-config
      uses: actions/checkout@v4
      with:
        repository: oss-review-toolkit/ort-config
        ref: "main"
        path: ".ort-config"

    - name: Setup ORT Config
      id: setup-ort-config
      shell: bash
      run: |
        mkdir -p "/$HOME/.ort/"

        # Move Fetched Default Config into Place
        mv .ort-config "/$HOME/.ort/config"
        
        # Append Global ORT Config
        cat .ort/config/config.yml >> "$HOME/.ort/config/config.yml"
        
        # Override Default Evaluator Rules
        cp .ort/config/evaluator.rules.kts "$HOME/.ort/config/evaluator.rules.kts"

    - name: "Cache ScanCode"
      uses: actions/cache@v4
      with:
        path: "~/.cache/scancode-tk"
        key: ${{ runner.os }}-scancode

    - name: Setup Package List
      id: setup-package-list
      uses: actions-able/envsubst-action@v1
      with:
        input-file: '.ort/package-list.yml'
        output-file: 'package-list.yml'
      env:
        GITHUB_SERVER_URL: "${{ github.server_url }}"
        GITHUB_REPOSITORY: "${{ inputs.repository }}"
        VERSION: "${{ inputs.version }}"

    - name: "Generate ORT Analyzer Result"
      id: generate_ort_analyzer_result
      shell: bash
      run: |
        mkdir -p "/$HOME/.ort/ort-results/"

        docker run \
          --entrypoint /opt/ort/bin/orth \
          --mount type=bind,source=$HOME,target=/home/ort \
          -u $(id -u):$(id -g) \
          -e JDK_JAVA_OPTIONS="-Xmx5120m" \
          -e ORT_DATA_DIR="/home/ort/.ort" \
          "$ORT_DOCKER_IMAGE" \
          create-analyzer-result-from-package-list \
          --package-list-file \
          "${PROJECT_PATH/$USER/ort}/package-list.yml" \
          --ort-file \
          "/home/ort/.ort/ort-results/analyzer-result.json"

        echo "========== LS"
        ls -al ~/.ort/ort-results/
        # Mirroring https://github.com/oss-review-toolkit/ort-ci-github-action/blob/2cda885c8eefaf92bab9f3e979b5d5a42970dfa4/action.yml#L473
        ln -frs "/$HOME/.ort/ort-results/analyzer-result.json" "/$HOME/.ort/ort-results/current-result.json"
      env:
        PROJECT_PATH: "${{ github.workspace }}"
        ORT_DOCKER_IMAGE: "ghcr.io/oss-review-toolkit/ort-minimal:latest"

    # TODO: Remove
    - name: DBG
      shell: bash
      run: |
        echo "===== Package List"
        cat package-list.yml
        echo "===== Analyzer Result"
        cat "/$HOME/.ort/ort-results/current-result.json"

    - name: Run OSS Review Toolkit
      id: ort
      # TODO: Use released version once the following issue has been released:
      # * https://github.com/oss-review-toolkit/ort-ci-github-action/issues/37
      # * https://github.com/oss-review-toolkit/ort-ci-github-action/pull/41
      # * https://github.com/oss-review-toolkit/ort-ci-github-action/pull/43
      uses: oss-review-toolkit/ort-ci-github-action@2cda885c8eefaf92bab9f3e979b5d5a42970dfa4 # main
      with:
        image: "ghcr.io/oss-review-toolkit/ort-minimal:latest"
        run: >
          labels,
          cache-dependencies,
          cache-scan-results,
          scanner,
          advisor,
          evaluator,
          reporter,
          ${{ inputs.upload-reports == 'true' && 'upload-results' || '' }}
        fail-on: "${{ inputs.fail-on-violation == 'true' && 'violations,issues' || '' }}"
        report-formats: "${{ inputs.report-formats }}"
        ort-cli-report-args: '-O CycloneDX=output.file.formats=json,xml -O SpdxDocument=outputFileFormats=JSON,YAML'
        sw-version: "${{ inputs.version }}"
