name: "Run OSS Review Toolkit"
description: "Runs OSS Review Toolkit & generates SBoMs"
inputs:
  build-artifacts:
    description: |
      Build Artifact paths to include into SBoM.
      May contain a glob pattern or list of paths separated by a newline.
    required: false
    default: ""
  report-formats:
    description: "ORT Report Formats"
    required: true
  fail-on-violation:
    description: "Whether to fail on violation."
    required: false
    default: false
  upload-reports:
    description: "Whether to upload all reports"
    required: false
    default: false
  version:
    desctiption: "Elixir Version (Tag / SHA)"
    required: true

outputs:
  results-path:
    description: "See oss-review-toolkit/ort-ci-github-action action"
    value: "${{ steps.ort.outputs.results-path }}"
  results-notice-path:
    description: "Path to resulting NOTICE file"
    value: "${{ steps.ort.outputs.results-path }}/NOTICE_DEFAULT"
  results-sbom-cyclonedx-xml-path:
    description: "See oss-review-toolkit/ort-ci-github-action action"
    value: "${{ steps.ort.outputs.results-sbom-cyclonedx-xml-path }}"
  results-sbom-cyclonedx-json-path:
    description: "See oss-review-toolkit/ort-ci-github-action action"
    value: "${{ steps.ort.outputs.results-sbom-cyclonedx-json-path }}"
  results-sbom-spdx-yml-path:
    description: "See oss-review-toolkit/ort-ci-github-action action"
    value: "${{ steps.ort.outputs.results-sbom-spdx-yml-path }}"

runs:
  using: "composite"
  steps:
    - name: Fetch Default ORT Config
      id: fetch-default-ort-config
      uses: actions/checkout@v4
      with:
        repository: oss-review-toolkit/ort-config
        ref: "main"
        path: ".ort-config"

    - name: Setup ORT Config
      id: setup-ort-config
      shell: bash
      run: |
        mkdir -p "/$HOME/.ort/"

        # Move Fetched Default Config into Place
        mv .ort-config "/$HOME/.ort/config"
        
        # Append Global ORT Config
        cat .ort/config/config.yml >> "$HOME/.ort/config/config.yml"
        
        # Override Default Evaluator Rules
        cp .ort/config/evaluator.rules.kts "$HOME/.ort/config/evaluator.rules.kts"
    
    # TODO: Add binary artifacts to ORT to have them included in the SBoM
    # Depends on some further work in ORT to correctly detect and name mix
    # applications.

    - name: "Cache ScanCode"
      uses: actions/cache@v4
      with:
        path: "~/.cache/scancode-tk"
        key: ${{ runner.os }}-scancode

    - name: Run OSS Review Toolkit
      id: ort
      # TODO: Use released version once the following issue has been released:
      # * https://github.com/oss-review-toolkit/ort-ci-github-action/issues/37
      # * https://github.com/oss-review-toolkit/ort-ci-github-action/pull/41
      # * https://github.com/oss-review-toolkit/ort-ci-github-action/pull/43
      uses: maennchen/ort-ci-github-action@action-output
      with:
        image: ghcr.io/oss-review-toolkit/ort-minimal:latest
        run: >
          labels,
          cache-dependencies,
          cache-scan-results,
          analyzer,
          scanner,
          advisor,
          evaluator,
          reporter,
          ${{ inputs.upload-reports == 'true' && 'upload-results' || '' }}
        fail-on: "${{ inputs.fail-on-violation == 'true' && 'violations,issues' || '' }}"
        report-formats: "${{ inputs.report-formats }}"
        sw-version: "${{ inputs.version }}"
